name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * *"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install tooling
        run: |
          pip install -U pip
          pip install ruff black pytest pytest-cov kafka-python requests tenacity
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Unit tests
        run: pytest -q

  compose-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose config


